version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-$(mix phx.gen.secret)}
      - DATABASE_URL=ecto://postgres:postgres@db/anoma_dev
      - TWITTER_CLIENT_ID=RG5ZOVoydWJlZ3FOSnVTa1dDTnA6MTpjaQ
      - TWITTER_CLIENT_SECRET=S3pqbDVZUGtHWjRrY3JmRGJUQWY6MTpjaQ
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=anoma_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: